apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      hostname: app-pod
      restartPolicy: Always
      containers:
        - name: app-fpm
          image: vasyakrg/php-app
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: MARIADB_HOST
            value: app-mariadb-service
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: myapp-mariadb-secret
                key: mariadb-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-mariadb-secret
                key: mariadb-password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: myapp-mariadb-secret
                key: mariadb-dbname
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp
  labels:
    app: myapp-mariadb
  name: myapp-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp-mariadb
    spec:
      hostname: myapp-mariadb-pod
      restartPolicy: Always
      containers:
        - name: myapp-db
          image: vasyakrg/php-db
          imagePullPolicy: Always
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-mariadb-secret
                key: mariadb-password
          - name: MARIADB_ROOT_HOST
            value: "%"
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: myapp-mariadb-secret
                key: mariadb-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-mariadb-secret
                key: mariadb-password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: myapp-mariadb-secret
                key: mariadb-dbname
          volumeMounts:
            - name: vol-myapp-mariadb
              mountPath: /var/lib/mysql
              subPath: mysql

      volumes:
        - name: vol-myapp-mariadb
          persistentVolumeClaim:
            claimName: myapp-db-pvc
