apiVersion: v1
kind: Secret
metadata:
  name: myapp-mariadb-secret
  namespace: myapp
data:
  mariadb-user: cmVzdHVzZXI=
  mariadb-password: dkVIQ1ZuN0NndXdGd0ViZXQySEMxQQ==
  mariadb-dbname: cmVzdGRi
---
