# App
apiVersion: v1
kind: Service
metadata:
  namespace: myapp
  name: app-service
spec:
  ports:
    - name: app-port
      port: 80
  selector:
    app: myapp
---

apiVersion: v1
kind: Service
metadata:
  namespace: myapp
  name: app-mariadb-service
spec:
  type: NodePort
  ports:
    - name: myapp-mariadb-port
      port: 3306
  selector:
    app: myapp-mariadb
---
