apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-db-pvc
  namespace: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
---
