apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: orc-letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@mail.ru
    privateKeySecretRef:
      name: orc-letsencrypt-private-key
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
